accounts/urls.py
from . import views
from django.urls import path

# set application name for urls
app_name = 'accounts'

urlpatterns = [
    path(route='profile', view=views.profile, name='profile'),
    path(route='member_table', view=views.memberTable, name='member_table'),
    path(route='member_search', view=views.memberSearch, name='member_search')
]

kaliroboda/urls.py
from . import views
from django.urls import path
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# handle page not found
handler404 = views.pageNotFound
# handle server error
handler500 = views.serverError

urlpatterns = [
    path(route='', view=views.dashbord, name='dashbord'),
    path(route='accounts/', view=include('accounts.urls')),
    path(route='admin/', view=admin.site.urls),
    path(route='home/', view=views.home, name='home'),
    path(route='export/', view=views.export_csv, name='export'),
    path(route='faqs', view=views.faqs, name='faqs'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models


# Create your models here.


class Member(models.Model):
    REQUIRED_FIELDS = ['first_name', 'last_name']
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female'), ('O', 'Other')]
    MEMEBER_STATUSES = [('A', 'Active'), ('N', 'Not Active')]

    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(verbose_name='Member email', blank=True)
    title = models.CharField(max_length=25)
    gender = models.CharField(choices=GENDER_CHOICES,
                              max_length=1, default="O")
    phone_number = models.CharField(max_length=25)
    display_picture = models.ImageField(
        default='display_pictures/smily.jpg', upload_to='display_pictures')
    district = models.CharField(max_length=25)
    village = models.CharField(max_length=25)
    stage = models.CharField(max_length=25)
    status = models.CharField(choices=MEMEBER_STATUSES,
                              default='T', max_length=1, verbose_name='Member Status', null=True)
    card_id = models.IntegerField(verbose_name="Membership card id")
    issue_date = models.DateTimeField(verbose_name="Date of issue of card")
    expiry_date = models.DateTimeField(verbose_name="Date of expiry of card")

    def __str__(self):
        return f'{self.last_name} {self.first_name}'
    

accounts/views.py
from .models import Member
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import redirect
from companyinfo.models import CompanyInfo

# Create your views here.


def fetchCompanyInfo():
    try:
        company_info = CompanyInfo.objects.values()[0]
    except Exception as e:
        company_info = {}
    return company_info


def profile(request):
    # get id sent as query on url string
    company_info = fetchCompanyInfo()
    member_id = request.GET.get('member_id')
    if member_id:
        try:
            # try finding the member
            member_profile = Member.objects.get(id=member_id)
            context = {'company_info': company_info,
                       'member_profile': member_profile}
            template_name = 'accounts/profile.html'
        except Member.DoesNotExist as e:
            # incase no member with the id is found
            context = {'company_info': company_info,
                       'error': 'No member info', 'message': e}
            template_name = 'kaliroboda/error.html'
    else:
        # if invalid member id has been provided on the url string
        context = {'company_info': company_info, 'error': 'Error catching requested member',
                   'message': 'The member id provided in the query seems invalid, contact admin for assistance'}
        template_name = 'kaliroboda/error.html'
    return render(request=request, template_name=template_name, context=context)

# handle settings request


def memberTable(request):
    # members = Member.objects.all().order_by('first_name')
    # context = {'members': members}
    company_info = fetchCompanyInfo()
    context = {'company_info': company_info}
    template_name = 'accounts/member_table.html'
    return render(request=request, template_name=template_name, context=context)

# handle member search


def memberSearch(request):
    # get query from form submission url

    query = request.GET.get('query')
    if query:
        company_info = fetchCompanyInfo()
        # find all members with the parameters containing the query
        results = Member.objects.filter(
            Q(first_name__icontains=query) | Q(last_name__icontains=query) | Q(
                email__icontains=query) | Q(card_id__icontains=query)
        )
        context = {'company_info': company_info,
                   'members': results, 'query': query}
        template_name = 'accounts/member_table.html'
    else:
        # in case no query was provided
        context = {'company_info': company_info, 'members': [], 'query': query}
        template_name = 'accounts/member_table.html'
    return render(request=request, template_name=template_name, context=context)

accounts/templates/accounts/member_table.html
{% extends 'kaliroboda/base.html' %} {% block content %}

<!-- New Table -->
<main class="container overflow-y-auto p-3">
  <!-- CTA -->
  <a
    class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
    href="{% url 'faqs'%}"
  >
    <div class="flex items-center">
      <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
        <path
          d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
        ></path>
      </svg>
      <span>Frequently Asked Questions</span>
    </div>
    <span>View now &RightArrow;</span>
  </a>
  <form action="{% url 'accounts:member_search' %}" method="get">
    {% csrf_token %}
    <label class="block mt-4 text-sm mb-3">
      <!-- <span class="text-gray-700 dark:text-gray-400"> Button right </span> -->
      <div class="relative text-gray-500 focus-within:text-purple-600">
        <input
          class="rounded py-2 border w-full pr-20 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input"
          {%
          if
          query
          %}
          placeholder="{{query}}"
          {%
          else
          %}
          placeholder=""
          {%
          endif
          %}
          type="text"
          name="query"
        />
        <button
          type="submit"
          class="absolute inset-y-0 right-0 px-4 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-r-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
        >
          Search
        </button>
      </div>
    </label>
  </form>
  {% if members %}
  <div class="w-full overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">Member</th>
            <th class="px-4 py-3">Card ID</th>
            <th class="px-4 py-3">Title</th>
            <th class="px-4 py-3">Status</th>
            <th class="px-4 py-3">Stage</th>
            <th class="px-4 py-3">Village</th>
            <th class="px-4 py-3">District</th>
            <th class="px-4 py-3">Phone Number</th>
            <th class="px-4 py-3">Gender</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
          {% for member in members %}
          <tr class="text-gray-700 dark:text-gray-400">
            <td class="px-4 py-3">
              <a
                href="{% url 'accounts:profile'%}?member_id={{member.id}}"
                class="flex items-center text-sm"
              >
                <!-- Avatar with inset shadow -->
                <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                  <img
                    class="object-cover w-full h-full rounded-full"
                    src="{{member.display_picture.url}}"
                    alt=""
                    loading="lazy"
                  />
                  <div
                    class="absolute inset-0 rounded-full shadow-inner"
                    aria-hidden="true"
                  ></div>
                </div>
                <div>
                  <p class="font-semibold">
                    {{member.first_name}} {{member.last_name}}
                  </p>
                  <p class="text-xs text-gray-600 dark:text-gray-400">Member</p>
                </div>
              </a>
            </td>
            <td class="px-4 py-3 text-sm">{{member.card_id}}</td>
            <td class="px-4 py-3 text-sm">{{member.title}}</td>
            <td class="px-4 py-3 text-sm">
              {% if member.status == 'A' %}
              <span
                class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100"
              >
                Active
              </span>
              {% elif member.status == 'N' %}
              <span
                class="px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full dark:text-white dark:bg-orange-600"
              >
                Inactive
              </span>
              {% else %}
              <span
                class="px-2 py-1 font-semibold leading-tight text-gray-700 bg-gray-100 rounded-full dark:bg-gray-700 dark:text-gray-100"
              >
                Pending
              </span>
              {% endif %}
            </td>
            <td class="px-4 py-3 text-sm">{{member.stage}}</td>
            <td class="px-4 py-3 text-sm">{{member.village}}</td>
            <td class="px-4 py-3 text-sm">{{member.district}}</td>
            <td class="px-4 py-3 text-sm">{{member.phone_number}}</td>
            <td class="px-4 py-3 text-sm">{{member.gender}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div
      class="grid py-3 text-xs font-semibold tracking-wide text-gray-500 border-t dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
    >
      <span class="flex items-center col-span-3"> End of table </span>
      <span class="col-span-2"></span>
      <!-- Pagination -->
    </div>
  </div>
  {% else %}
  <h2 class="text-white">
    No members found, search members by ID, First Name, Last Name, or Email
  </h2>
  {% endif %} {% endblock %}
</main>

accounts/templates/accounts/profile.html
{% extends 'kaliroboda/base.html'%} {% block content%}
<main class="p-4 pb-16 overflow-y-auto">
  <form
    action=""
    method="post"
    enctype="multipart/form-data"
    class="container px-6 mx-auto grid"
  >
    {% csrf_token %}

    <div
      class="pt-2 text-center border border-yellow-500 min-w-0 p-4 bg-yellow-200 rounded-lg shadow-xs dark:bg-yellow-200"
    >
      <div class="flex flex-col space-y-2 mb-4 font-semibold text-yellow-600">
        <i class="fa-solid fa-beat-fade fa-triangle-exclamation text-3xl"></i>
        <h4>Notice!</h4>
      </div>
      <p class="text-yellow-600">
        You cannot change account info, contact admin for help.
      </p>
    </div>
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      Member Profile
    </h2>
    <div class="py-5">
      <img
        class="m-auto object-cover w-[10rem] h-[10rem] rounded"
        src="{{member_profile.display_picture.url}}"
        alt=""
        aria-hidden="true"
      />
    </div>
    <div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
      <label class="block py-2 text-sm">
        <span class="text-gray-700 dark:text-gray-400">First Name</span>
        <input
          class="p-2 border rounded block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder="Jane Doe"
          name="first_name"
          value="{{member_profile.first_name}}"
          required
          disabled
        />
      </label>
      <label class="block py-2 text-sm">
        <span class="text-gray-700 dark:text-gray-400">Last Name</span>
        <input
          class="p-2 border rounded block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder="Jane Doe"
          name="last_name"
          value="{{member_profile.last_name}}"
          required
          disabled
        />
      </label>
      <label class="block py-2 text-sm">
        <span class="text-gray-700 dark:text-gray-400">Email</span>
        <input
          class="p-2 border rounded block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder="Jane Doe"
          name="email"
          value="{{member_profile.email}}"
          disabled
        />
      </label>
      </label>
      <label class="block text-sm py-2">
        <span class="text-gray-700 dark:text-gray-400">Gender</span>
        <input
          class="p-2 rounded border block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder="gender"
          type="text"
          name="membername"
          value="{{member_profile.gender}}"
          required
          disabled
        />
      </label>
      <label class="block text-sm py-2">
        <span class="text-gray-700 dark:text-gray-400">Stage</span>
        <input
          class="p-2 rounded border block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder=""
          type="text"
          name="membername"
          value="{{member_profile.stage}}"
          required
          disabled
        />
      </label>
      <label class="block text-sm py-2">
        <span class="text-gray-700 dark:text-gray-400">Phone Number</span>
        <input
          class="p-2 rounded border block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder=""
          type="text"
          name="membername"
          value="{{member_profile.phone_number}}"
          required
          disabled
        />
      </label>
      <label class="block text-sm py-2">
        <span class="text-gray-700 dark:text-gray-400">Card ID</span>
        <input
          class="p-2 rounded border block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder=""
          type="text"
          name="membername"
          value="{{member_profile.card_id}}"
          required
          disabled
        />
      </label>
      <label class="block text-sm py-2">
        <span class="text-gray-700 dark:text-gray-400">Card Issue Date</span>
        <input
          class="p-2 rounded border block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder=""
          type="text"
          name="membername"
          value="{{member_profile.issue_date}}"
          required
          disabled
        />
      </label>
      <label class="block text-sm py-2">
        <span class="text-gray-700 dark:text-gray-400">Card Expiry Date</span>
        <input
          class="p-2 rounded border block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
          placeholder=""
          type="text"
          name="membername"
          value="{{member_profile.expiry_date}}"
          required
          disabled
        />
      </label>
      <div class="flex mt-6 text-sm">
        <label class="flex items-center dark:text-gray-400">
          <input
            type="checkbox"
            required
            disabled
            class="text-purple-600 form-checkbox focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray"
          />
          <span class="ml-2">
            I agree to the
            <span class="underline">privacy policy</span>
          </span>
        </label>
      </div>
    </div>
    <div>
      <!-- <button
        type="submit"
        class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
      >
        Regular
      </button> -->
    </div>
  </form>
</main>
{% endblock %}

accounts/templates/accounts/user_table.html
{% extends 'kaliroboda/base.html' %} {% block content %}

<!-- New Table -->
<main class="container overflow-y-auto p-3">
  <!-- CTA -->
  <a
    class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
    href=""
  >
    <div class="flex items-center">
      <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
        <path
          d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
        ></path>
      </svg>
      <span>Frequently Asked Questions</span>
    </div>
    <span>View now &RightArrow;</span>
  </a>
  <form action="{% url 'accounts:user_search' %}" method="get">
    {% csrf_token %}
    <label class="block mt-4 text-sm mb-3">
      <!-- <span class="text-gray-700 dark:text-gray-400"> Button right </span> -->
      <div class="relative text-gray-500 focus-within:text-purple-600">
        <input
          class="rounded py-2 border w-full pr-20 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input"
          {%
          if
          query
          %}
          placeholder="{{query}}"
          {%
          else
          %}
          placeholder="John Doe"
          {%
          endif
          %}
          type="text"
          name="query"
        />
        <button
          type="submit"
          class="absolute inset-y-0 right-0 px-4 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-r-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
        >
          Search
        </button>
      </div>
    </label>
  </form>
  {% if users %}
  <div class="w-full overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">User</th>
            <th class="px-4 py-3">Card ID</th>
            <th class="px-4 py-3">Status</th>
            <th class="px-4 py-3">Date</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
          {% for user in users %}
          <tr class="text-gray-700 dark:text-gray-400">
            <td class="px-4 py-3">
              <a
                href="{% url 'accounts:profile'%}?user_id={{user.id}}"
                class="flex items-center text-sm"
              >
                <!-- Avatar with inset shadow -->
                <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                  <img
                    class="object-cover w-full h-full rounded-full"
                    src="{{user.display_picture.url}}"
                    alt=""
                    loading="lazy"
                  />
                  <div
                    class="absolute inset-0 rounded-full shadow-inner"
                    aria-hidden="true"
                  ></div>
                </div>
                <div>
                  <p class="font-semibold">
                    {{user.first_name}} {{user.last_name}}
                  </p>
                  <p class="text-xs text-gray-600 dark:text-gray-400">User</p>
                </div>
              </a>
            </td>
            <td class="px-4 py-3 text-sm">{{user.id}}</td>
            <td class="px-4 py-3 text-xs">
              <span
                class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100"
              >
                {% if user.member %}
                <span>Member</span>
                {% elif user.is_staff %}
                <span>Staff</span>
                {% else %}
                <span>Other</span>
                {% endif %}
              </span>
            </td>
            <td class="px-4 py-3 text-sm">{{user.gender}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div
      class="grid py-3 text-xs font-semibold tracking-wide text-gray-500 border-t dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
    >
      <span class="flex items-center col-span-3"> End of table </span>
      <span class="col-span-2"></span>
      <!-- Pagination -->
    </div>
  </div>
  {% else %}
  <h2 class="text-white">No users found</h2>
  {% endif %} {% endblock %}
</main>